In [1]:
import boto3
import pandas as pd

In [11]:
from boto3.session import Session
import io

ACCESS_KEY='AKIAXPJHEGASZIZGKQ5A'
SECRET_KEY='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'
bucket= 'balbi-finance-app'

s3 = boto3.client(
    's3', 
    region_name='us-east-1', 
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY
)

df_list = []
response = s3.list_objects(Bucket=bucket)
request_files = response["Contents"]
for file in request_files:
    obj = s3.get_object(Bucket=bucket, Key=file["Key"])
    if file["Key"].find('datasets/posicao/') >= 0:
        print('Posicao: {}'.format(file["Key"]))
        df_pos_ = pd.read_excel(io.BytesIO(obj['Body'].read()))
        df_list.append(df_pos_)
    elif file["Key"].find('datasets/extrato/Extrato.csv') >= 0:
        print('Extrato: {}'.format(file["Key"]))
        df_extrato = pd.read_csv(obj["Body"], sep=';', decimal=',')
    elif file["Key"].find('datasets/acoes/extrato_acoes.xlsx') >= 0:
        print('Extrato ações: {}'.format(file["Key"]))
        #df_extacoes = pd.read_excel(obj["Body"], sheet_name='Planilha2')
        df_extacoes = pd.read_excel(io.BytesIO(obj['Body'].read()), sheet_name='Planilha2')
        
    
    #obj_df = pd.read_csv(obj["Body"])
    #df_list.append(obj_df)

#df = pd.concat(df_list)

df_extacoes.head()

Extrato ações: datasets/acoes/extrato_acoes.xlsx
Extrato: datasets/extrato/Extrato.csv
Posicao: datasets/posicao/-PosicaoHistorico_200091-10.xls
WARNING *** file size (60570) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-3 2.xls
WARNING *** file size (71838) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-4 2.xls
WARNING *** file size (71834) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-5 - cópia.xls
WARNING *** file size (69788) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-7.xls
WARNING *** file size (60570) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-8.xls
WARNING *** file size (60570) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/-PosicaoHistorico_200091-9.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-10.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-11.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-12.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-13.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-14.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-15.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-16.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-17.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-18.xls
WARNING *** file size (59546) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-19.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-2.xls
WARNING *** file size (78490) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-20.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-21.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-22.xls
WARNING *** file size (59548) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-23.xls
WARNING *** file size (58524) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-24.xls
WARNING *** file size (58522) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-25.xls
WARNING *** file size (58522) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-26.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-27.xls
WARNING *** file size (60570) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-28.xls
WARNING *** file size (58526) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-29.xls
WARNING *** file size (59034) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-3 2.xls
WARNING *** file size (75418) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-3.xls
WARNING *** file size (65692) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-30.xls
WARNING *** file size (57498) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-31.xls
WARNING *** file size (57500) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-32.xls
WARNING *** file size (55452) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-33.xls
WARNING *** file size (59470) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-34.xls
WARNING *** file size (54430) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-35.xls
WARNING *** file size (54428) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-36.xls
WARNING *** file size (54426) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-37.xls
WARNING *** file size (54426) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-38.xls
WARNING *** file size (54428) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-39.xls
WARNING *** file size (54426) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-4 2.xls
WARNING *** file size (77466) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-4.xls
WARNING *** file size (66716) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-40_.xls
WARNING *** file size (54428) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-41.xls
WARNING *** file size (49820) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-42.xls
WARNING *** file size (49820) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-43.xls
WARNING *** file size (49822) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-5 2.xls
WARNING *** file size (75420) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-5.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-55.xls
WARNING *** file size (72346) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-56.xls
WARNING *** file size (49820) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-57.xls
WARNING *** file size (49820) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-58.xls
WARNING *** file size (49820) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-59.xls
WARNING *** file size (49818) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-5_.xls
WARNING *** file size (65696) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-6 - cópia.xls
WARNING *** file size (70812) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-6-.xls
WARNING *** file size (65180) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-6.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-60.xls
WARNING *** file size (56476) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-61.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-62.xls
WARNING *** file size (56476) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-63.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-64.xls
WARNING *** file size (56476) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-65.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-66.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)

Posicao: datasets/posicao/PosicaoHistorico_200091-67.xls
WARNING *** file size (57500) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-68.xls
WARNING *** file size (56480) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-69.xls
WARNING *** file size (56476) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-7 - cópia.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-7.xls
WARNING *** file size (60574) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-70.xls
WARNING *** file size (56988) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-71.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-72.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-73.xls
WARNING *** file size (56474) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-74.xls
WARNING *** file size (55452) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-75.xls
WARNING *** file size (55450) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-8.xls
WARNING *** file size (60572) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091-9.xls
WARNING *** file size (59550) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_200091.xls
WARNING *** file size (74908) not 512 + multiple of sector size (512)
Posicao: datasets/posicao/PosicaoHistorico_202011.xls
WARNING *** file size (76956) not 512 + multiple of sector size (512)

    Papel Categoria    Tipo  Qtde  Preco       Data
0  MSFT34      ACAO  COMPRA    50  47.93 2020-12-30
1  BCFF11       FII  COMPRA    58  88.60 2020-12-17
2   MGLU3      ACAO   VENDA   700  24.50 2020-12-16
3  NVDC34      ACAO  COMPRA    90  56.77 2020-12-16
4  PFIZ34      ACAO  COMPRA    20  52.00 2020-12-11

In [12]:
df_extrato.head()

,Liq,Mov,Descricao,Valor,Saldo
0,04/06/2020,04/06/2020,* PROV * DEBITO CBLC IRRF S/ RENDIMENTO DE BTC...,-0.01,58.23
1,04/06/2020,04/06/2020,* PROV * CrŽdito Ref. Taxa de Remunera‹o BTC ...,0.06,58.24
2,01/06/2020,28/05/2020,OPERA‚ÍES EM BOLSA PR 28/05/2020 NOTA N¼ 22035030,-8419.82,58.18
3,28/05/2020,28/05/2020,TED - RECEBIMENTO DE TED - SPB,7000.00,8478.00
4,28/05/2020,28/05/2020,RENDIMENTOS DE CLIENTES CNES11 S/ 11,1.81,1478.00

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,NaN,XP Investimentos CCTVM S/A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,"Praia de Botafogo, 501 - Sala 601 A1\nBotafogo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
session = Session(aws_access_key_id=ACCESS_KEY,
                  aws_secret_access_key=SECRET_KEY)
s3 = session.resource('s3')
app_bucket = s3.Bucket('balbi-finance-app')

for s3_file in app_bucket.objects.all():
#    print(s3_file.key)
    if s3_file.key.find('datasets/posicao/') >= 0:
        print('Posicao: {}'.format(s3_file.key))
    elif s3_file.key.find('datasets/extrato/Extrato.csv') >= 0:
        print('Extrato: {}'.format(s3_file.key))
    elif s3_file.key.find('datasets/acoes/extrato_acoes.xlsx') >= 0:
        print('Extrato ações: {}'.format(s3_file.key))

Extrato ações: datasets/acoes/extrato_acoes.xlsx
Extrato: datasets/extrato/Extrato.csv
Posicao: datasets/posicao/-PosicaoHistorico_200091-10.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-3 2.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-4 2.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-5 - cópia.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-7.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-8.xls
Posicao: datasets/posicao/-PosicaoHistorico_200091-9.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-10.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-11.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-12.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-13.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-14.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-15.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-16.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-17.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-18.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-19.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-2.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-20.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-21.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-22.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-23.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-24.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-25.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-26.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-27.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-28.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-29.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-3 2.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-3.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-30.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-31.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-32.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-33.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-34.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-35.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-36.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-37.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-38.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-39.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-4 2.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-4.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-40_.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-41.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-42.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-43.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-5 2.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-5.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-55.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-56.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-57.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-58.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-59.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-5_.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-6 - cópia.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-6-.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-6.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-60.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-61.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-62.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-63.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-64.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-65.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-66.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-67.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-68.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-69.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-7 - cópia.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-7.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-70.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-71.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-72.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-73.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-74.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-75.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-8.xls
Posicao: datasets/posicao/PosicaoHistorico_200091-9.xls
Posicao: datasets/posicao/PosicaoHistorico_200091.xls
Posicao: datasets/posicao/PosicaoHistorico_202011.xls